#spring.datasource.url=jdbc:h2:file:./Pokando
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring.datasource.url=jdbc:postgresql://localhost:5432/pokando
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
#spring.datasource.password=123456
spring.datasource.password=1234
#spring.datasource.password=ifms



spring.jpa.show-sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

spring.h2.console.enabled=false

# --- Configuração do Google OAuth 2.0 ---
# USE VARIÁVEIS AQUI, NÃO AS SENHAS REAIS

# Força o cookie a ser válido em todo o domínio (para o front conseguir ler)
server.servlet.session.cookie.path=/
